weba:
    build: .
    expose:
        - 8080

webb:
    build: .
    expose:
        - 8080

webc:
    build: .
    expose:
        - 8080

haproxy:
    build: .
    links:
        - weba
        - webb
        - webc
    ports:
        - "8080:8080"
        - "80:80"
        - "70:70"
    expose:
        - "80"
        - "70"